- hosts: lnlxspw01
  vars:
    admin_users:
      - login: stevene
        groups: sp_users
        password: $6$sGcYQwxn$JB6vMtam6I.ygu2M20vNA7dqGhPqW5UlLRAOl7Kl.hbcMg7bwxmJ6MbvwdgmhECCZ0sHRnoVYeRYVeWrwHCxN1
      - login: andrew
        groups: sp_users
        password: $6$GaXceflm$Xaw3meaIcNLzFlxQf9266WwBVmx/Qf.IDaLr5ugKTMG2If9gwFnyZg4GY5JGObfRJQPXb2PxX5u/K3U8Kr6jn1
      - login: paul
        groups: sp_users
        password: $6$drqlyTQF$ooqOYEvRyNOo4vhCrgAITWAF2c.gBCk.yNvmtenKqmnHtuuFF18kk6WKQhBaMaBp7H2CJoG4.KmpNfZ6BeIZ2/
      - login: charlie
        groups: sp_users
        password: $6$VnYmZPXa$/fZiLUFGgLrEL8EQimbcreBYtZOsSsM0PdlOUlHTX1uS/vkEDulebFQo8KiY3N.q28UQm0WJZ.5xdGBfP9qSh1
      - login: evansa
        groups: sp_users
        password: $6$EfwPtaTe$NFa/KLM0V58JmQtgfkfmNwv/cmIv0iEV0OuwAYNEEHT8cZHbHq0L5HRjr5br9TC8RezzFOy7v2xdlTmsZfhoR.
      - login: krpa
        groups: sp_users
        password: $6$qvVZHpRJ$CGx2PWcPi.lWtSzCb8tdMxV/ZWHQw7gXkWyvppZrU5pJAxCH.drbULL52InHr1bBU2OtL1zqoFOWDAGOSzpmk1
      - login: avpa
        groups: sp_users
        password: $6$TMreZdDF$sV9G4WnMrv4FSPWJxAUbJflFg.prau6QDwNZ1JjvslSw9mMnwb1G7nkYGX1LJhbLIIEgPS6uJ4pWJizx71rwV1

  tasks:
## REGISTER SERVER TO SPACEWALK
  - name: Ansible copy RHN-Register folder from Spacewalk to Target Server
    copy:
     src: /var/satellite/RHN-Register
     dest: /var/tmp

  - name: Create a directory if it does not exist
    file:
     path: /etc/yum.repos.d/BACKUP
     state: directory
     mode: '0755'

  - name: Shell yum clean all
    shell: /usr/bin/yum clean all
    args:
      executable: /bin/bash
      warn: no
      creates: /etc/yum.repos.d/CentOS-Base.repo

  - name: Shell copy repo files to BACKUP directory
    shell: /usr/bin/mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/BACKUP
    args:
      executable: /bin/bash
      warn: no
      creates: /etc/yum.repos.d/BACKUP/CentOS-Base.repo

#  - name: Remove repository (and clean up left-over metadata)
#    yum_repository:
#      name: base/7/x86_64 extras/7/x86_64 updates/7/x86_64
#      state: absent
#      notify: yum-clean-metadata

#  - name: Remove file (delete file)
#    file:
#     path: /etc/yum.repos.d/*.repo
#     state: absent

  - name: YUM install RHN-Register PART I and pre-requisites from local file
    yum:
      name: /var/tmp/RHN-Register/libnl-1.1.4-3.el7.x86_64.rpm, /var/tmp/RHN-Register/m2crypto-0.21.1-17.el7.x86_64.rpm, /var/tmp/RHN-Register/pyOpenSSL-0.13.1-4.el7.x86_64.rpm, /var/tmp/RHN-Register/python-dmidecode-3.12.2-3.el7.x86_64.rpm, /var/tmp/RHN-Register/python-ethtool-0.8-8.el7.x86_64.rpm, /var/tmp/RHN-Register/python-gudev-147.2-7.el7.x86_64.rpm, /var/tmp/RHN-Register/python-hwdata-1.7.3-4.el7.noarch.rpm, /var/tmp/RHN-Register/yum-rhn-plugin-2.0.1-10.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-check-2.0.2-24.el7.x86_64.rpm, /var/tmp/RHN-Register/rhn-client-tools-2.0.2-24.el7.x86_64.rpm, /var/tmp/RHN-Register/rhnlib-2.5.65-8.el7.noarch.rpm, /var/tmp/RHN-Register/rhnsd-5.0.13-10.el7.x86_64.rpm, /var/tmp/RHN-Register/rhn-setup-2.0.2-24.el7.x86_64.rpm, /var/tmp/RHN-Register/rhn-client-tools-2.0.2-24.el7.x86_64.rpm
      state: present
      disable_gpg_check: yes

  - name: YUM install RHN-Register PART II and pre-requisites from local file
    yum:
      name: /var/tmp/RHN-Register/python2-rhn-check-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-rhnlib-2.9.5-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-rhn-client-tools-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-rhn-setup-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-client-tools-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-setup-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-check-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/yum-rhn-plugin-2.9.5-1.el7.noarch.rpm
      state: present
      disable_gpg_check: yes


## yum-rhn-plugin - disable GPG check
  - name: yum-rhn-plugin update GPG check 0 in /etc/yum/pluginconf.d/rhnplugin.conf
    lineinfile:
     path: /etc/yum/pluginconf.d/rhnplugin.conf
     insertafter: '#gpgcheck = 0'
     line: 'gpgcheck = 0'
     backup: yes

## RHN-register
  - name: rhn-register as with activation key
    rhn_register:
      state: present
      activationkey: 1-21ad0fddf8f510baf82b58788f384190
      server_url:  http://192.168.130.76/XMLRPC
#      channels: centos-7-base-x86_64

## RHN-register add software channels
#  - name: rhn-register add software base channels
#    rhn_register:
#      state: present
#      activationkey: 1-21ad0fddf8f510baf82b58788f384190
#      channels: 'Centos 7 Base x86_64'


## Spacewalk osad packages install
  - name: YUM install osad Spacewalk packages
    yum:
      name: /var/tmp/RHN-Register/python2-rhnlib-2.9.5-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-rhn-client-tools-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-setup-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-rhn-check-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-rhn-setup-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-client-tools-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/jabberpy-0.5-0.27.el7.noarch.rpm, /var/tmp/RHN-Register/python2-osa-common-5.11.107-1.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-check-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/spacewalk-usix-2.9.1-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-spacewalk-usix-2.9.1-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-osad-5.11.107-1.el7.noarch.rpm, /var/tmp/RHN-Register/osad-5.11.107-1.el7.noarch.rpm
      state: present
      disable_gpg_check: yes

## Add SpaceWalk SSL certificate to host
  - name: Ansible copy SpaceWalk SSL cert to target server
    copy:
     src: /var/www/html/pub/RHN-ORG-TRUSTED-SSL-CERT
     dest: /usr/share/rhn/


## Spacewalk openscap client
  - name: YUM install spacewalk-oscap (openScap)
    yum:
      name: /var/tmp/RHN-Register/spacewalk-oscap-2.9.5-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-spacewalk-oscap-2.9.5-1.el7.noarch.rpm
      state: present
      disable_gpg_check: yes


## ADD FIREWALL RULES
# Firewalld - enable sftp/ssh services
  - name:  Firewalld enbable services
    firewalld:
       service: "{{ item }}"
       permanent: yes
       state: enabled
    loop:
      - ssh


## ADD ADMIN USERS AND GROUPS
# Add sp_users group
  - name: Add sp_users group
    group:
     name: sp_users
     state: present

# Add sp_users accounts locally
  - name: Add sp_users accounts locally
    user:
      name: "{{ item.login }}"
      groups: "{{ item.groups }}"
      shell: /bin/bash
      append: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa.key
      comment: "Privileged User"
      append: yes
      password: "{{ item.password }}"
#      update_password: on_create
    loop: "{{ admin_users }}"

# Add sp_users entries to /etc/sudoers
  - name: Adding sp_users to /etc/sudoers
    lineinfile:
      owner: root
      group: root
      dest: /etc/sudoers
      backup: yes
      validate: /usr/sbin/visudo -cf %s
      line: '{{ item }}'
    with_items:
      - ''
      - '## sp_users'
      - 'Cmnd_Alias SP_USERS = /bin/firewall-cmd, /bin/systemctl, /sbin/reboot, /usr/bin/vi /etc/hosts, /bin/vim /etc/hosts, /usr/bin/su -'
      - '%sp_users      ALL=(ALL)        SP_USERS'


# yum install snmp @ latest
  - name: YUM install snmp and dependencies @ latest
    yum:
      name:  net-snmp, net-snmp-utils, net-snmp-agent-libs, net-snmp-libs
      state: present

## INSTALL 3RD-PARTY SOFTWARE
# Copy 3rd-Party dir from spacewalk to host
  - name:  Ansible copy /var/satellite/3rd-Party directory from Spacewalk to Target Server
    copy:
     src: /var/satellite/3rd-Party
     dest: /var/tmp

# Yum install rsyslog
  - name: install rsyslog
    yum:
      name: rsyslog
      state: present


# rsyslog add eventengine target to rsyslog.conf
  - name: Add target eventengine host to /etc/rsyslog.conf
    lineinfile:
     path: /etc/rsyslog.conf
     insertafter: '#*.* @@remote-host:514'
     line: '*.*  @@192.168.33.23:514'
     backup: yes
     create: yes

# rsyslog - restart service/start service
  - name:  Service rsyslogd enable/reload/start
    service:
      name: rsyslog
      state: restarted

# Yum install Crowdstrike RPM.
  - name: install Crowdstrike from local file
    yum:
      name: /var/tmp/3rd-Party/falcon-sensor-5.23.0-8705.el7.x86_64.rpm
      state: present
      disable_gpg_check: yes

# CrowdStrike - set customer number
  - name: Crowdstrike - Register/set Customer ID CID
    shell: /opt/CrowdStrike/falconctl -s -f --cid=ED53295E363C4DA4B8AC5B4E727E2337-7F
    args:
      executable: /bin/bash
      creates: /opt/CrowdStrike/Registry.bin

# Crowdstrike - enable service/start service
#  - name:  Service Crowdstrike (falcon-sensor)enable/reload/start
#    service:
#      name: falcon-sensor
#      state: reloaded

# Crowdstrike - restart service/start service
  - name:  Service Crowdstrike (falcon-sensor)enable/reload/start
    service:
      name: falcon-sensor
      state: restarted

# yum remove older git 1.18
  - name: YUM remove git-1.8.3.1-20.el7.x86_642.22.2
    yum:
      name:  git-1.8.3.1-20.el7.x86_64
      state: absent

# yum install git 2.22.2 (stage on spwacewalk server form IUS repo)
  - name: YUM install git @ 2.22.2 (staged on spwacewalk server form IUS repo)
    yum:
      name:  /var/tmp/3rd-Party/git222-2.22.2-1.el7.ius.x86_64.rpm, /var/tmp/3rd-Party/git222-core-2.22.2-1.el7.ius.x86_64.rpm, /var/tmp/3rd-Party/git222-core-doc-2.22.2-1.el7.ius.noarch.rpm, /var/tmp/3rd-Party/git222-perl-Git-2.22.2-1.el7.ius.noarch.rpm
      state: present


## TIDY UP TEMPORARY WORKING DIRECTORIES
## RHN-Register clean up /var/tmp/RHN-Register working directory
  - name: Clean-up remove /var/tmp/RHN-Register directory
    file:
     path: /var/tmp/RHN-Register
     state: absent

## 3rd-Party clean up /var/tmp/3rd-Party working directory
  - name: Clean-up remove /var/tmp/RHN-Register directory
    file:
     path: /var/tmp/3rd-Party
     state: absent
