- hosts: TARGET
  vars:
    admin_users:
      - login: superlinux
        groups: wheel
        password: $6$U9YOVlh1$ULzP1yyjPl.tCDbpStoLaxMVy6dCFg10FvluL355h1eN6AFuP0HgCC5QSAdR6v4VmJrqh5tFEolp7klLYSUlJ1
      - login: stevene
        groups: sp_users,xrdpusers
        password: $6$sGcYQwxn$JB6vMtam6I.ygu2M20vNA7dqGhPqW5UlLRAOl7Kl.hbcMg7bwxmJ6MbvwdgmhECCZ0sHRnoVYeRYVeWrwHCxN1
      - login: andrew
        groups: sp_users,xrdpusers
        password: $6$GaXceflm$Xaw3meaIcNLzFlxQf9266WwBVmx/Qf.IDaLr5ugKTMG2If9gwFnyZg4GY5JGObfRJQPXb2PxX5u/K3U8Kr6jn1
      - login: arpa
        groups: sp_users,xrdpusers
        password: $6$GaXceflm$Xaw3meaIcNLzFlxQf9266WwBVmx/Qf.IDaLr5ugKTMG2If9gwFnyZg4GY5JGObfRJQPXb2PxX5u/K3U8Kr6jn1
      - login: paul
        groups: sp_users,xrdpusers
        password: $6$drqlyTQF$ooqOYEvRyNOo4vhCrgAITWAF2c.gBCk.yNvmtenKqmnHtuuFF18kk6WKQhBaMaBp7H2CJoG4.KmpNfZ6BeIZ2/
      - login: pgpa
        groups: sp_users,xrdpusers
        password: $6$drqlyTQF$ooqOYEvRyNOo4vhCrgAITWAF2c.gBCk.yNvmtenKqmnHtuuFF18kk6WKQhBaMaBp7H2CJoG4.KmpNfZ6BeIZ2/
      - login: charlie
        groups: sp_users,xrdpusers
        password: $6$VnYmZPXa$/fZiLUFGgLrEL8EQimbcreBYtZOsSsM0PdlOUlHTX1uS/vkEDulebFQo8KiY3N.q28UQm0WJZ.5xdGBfP9qSh1
      - login: crpa
        groups: sp_users,xrdpusers
        password: $6$VnYmZPXa$/fZiLUFGgLrEL8EQimbcreBYtZOsSsM0PdlOUlHTX1uS/vkEDulebFQo8KiY3N.q28UQm0WJZ.5xdGBfP9qSh1
      - login: evansa
        groups: sp_users,xrdpusers
        password: $6$EfwPtaTe$NFa/KLM0V58JmQtgfkfmNwv/cmIv0iEV0OuwAYNEEHT8cZHbHq0L5HRjr5br9TC8RezzFOy7v2xdlTmsZfhoR.
      - login: eapa
        groups: sp_users,xrdpusers
        password: $6$EfwPtaTe$NFa/KLM0V58JmQtgfkfmNwv/cmIv0iEV0OuwAYNEEHT8cZHbHq0L5HRjr5br9TC8RezzFOy7v2xdlTmsZfhoR.
      - login: krpa
        groups: sp_users,xrdpusers
        password: $6$qvVZHpRJ$CGx2PWcPi.lWtSzCb8tdMxV/ZWHQw7gXkWyvppZrU5pJAxCH.drbULL52InHr1bBU2OtL1zqoFOWDAGOSzpmk1
      - login: avpa
        groups: sp_users,xrdpusers
        password: $6$TMreZdDF$sV9G4WnMrv4FSPWJxAUbJflFg.prau6QDwNZ1JjvslSw9mMnwb1G7nkYGX1LJhbLIIEgPS6uJ4pWJizx71rwV1
    dev_users:
      - login: ngsd
        groups: devs,xrdpusers,ECA,DevMan
        password: $6$LSjGBEPC$5NPwAHr7WKHo3qV6sc3uftlhUUy3MYKaYZu0aFyS/.tr/h1IEYnMzhppEl8s4B8ajBf3Mh8jqe5c.8lATozOL/
      - login: rssd
        groups: devs,xrdpusers,ECA,DevMan
        password: $6$FNEvyJnR$2UPjtLV.spgsteetoQ1gLEUO93TG3FzjTByXWpXY5JK1qUVaVCZoxscvwcMDV672BxP14MV3r31ghMRLzkOc.0
      - login: wgsd
        groups: devs,xrdpusers,ECA,DevLead
        password: $6$ONnrSRxs$7FG8RAhoX2rWepUo42pn3wl2zMPI91KaSqMNq4gA8V55FJX8HV4tFOdfc9ifWvGCQb9l7xFJ6x3MbAxZ/3Kpy/
      - login: mmsd
        groups: devs,xrdpusers,ECA,DevLead
        password:
      - login: apsd
        groups: devs,xrdpusers,ECA
        password: $6$HAcZMuLj$SjaCaKDUWNitnPwodAsvYuJeJND2ugQhardupMfErGKa5/vpdAiQ2a93AH40yIRw7A.7GS0nGwCYx/0UPO/Sp0
      - login: shsd
        groups: devs,xrdpusers,ECA
        password: $6$VTUOdXcA$MtQ2UzWgLk4wxDj2Ny9F..TOT776B.WZNhDywoRb2fLZIs2Kzdzy5vFoqYR7Nype9UfHtKSdvOhuHgskIkgtD1
      - login: iksd
        groups: devs,xrdpusers,ECA
        password: $6$3keSVpCR$H1N5BP7TIywfAh8aMOI64ciWS/f7qlww4cL8r17HxlkDgKOyqDCUBh20AbVPWTHCzMhOOWeEfGaTG2vVQqcrb0
      - login: ngsd
        groups: devs,xrdpusers,ECA
        password: $6$udnlzLCE$v.Tvpp1RJon3ZRNXzZ3KnUOrCGxhVVOZFqzqPo98ih0pZvEfw.A/qEAO5cF4mL84SZGL8vxf.RZfbCqORcAdg0
      - login: gksd
        groups: devs,xrdpusers,ECA
        password: $6$56ZsHxUt$IOg/gQYoRAF1op8uQ4Z186OH.603.0rBjSCvv66QN.ErnyZzbuXpWY.AIrw7CFNdC0mNvVVm/IkVejdvql5xC.
      - login: ssasd
        groups: devs,xrdpusers,ECA
        password: $6$SrAjlNnM$Pmkip8AAGbGiAlH1vJEOJxw8vdDYp8DboDOtKsYH9iKcyz89p6bmSZNWFoMJvs3rHqCMFcSOI7INT4EBWtLB90

############################################
# CHANGES
# 2020/01/31 - new usernames for all dev accounts
# 2020/01/31 - added 2nd Admin accounts for Andre/Paul/Charlei/Evans - as these will match up in AD once they change them over
# 2020/01/31 - account sssd matches system acocunt, hence new username ssasd
# 2020/02/11 - t'internet check to allow yml to be omnipient/not dependency upion t'internet being enabled
#
###########################################
#      - login: ECABuildRelease
#        groups:
#        password:
#      - login: ECAReleaseBuilder
#        groups:

#  - import_playbook: snmp_config.yml

  tasks:
#  - name: Use uri to check t'internet
#    uri:
#      url: http://scootersoftware.com
#      return_content: no
#      timeout: 10
#    register:  tinternet_disabled
#    failed_when: "{{ tinternet_disabled.msg == 'Status code was -1 and not [200]:' }}"
#    ignore_errors: true
#  - debug:
##      msg: "{{ tinternet_disabled.status }}"
#      msg: "{{ tinternet_disabled }}"

## Handler to clean up yum metadata
#  - name: yum-clean-metadata
#    command: yum clean metadata
#    args:
#      warn: no

## REGISTER SERVER TO SPACEWALK
  - name: Ansible copy RHN-Register folder from Spacewalk to Target Server
    copy:
     src: /var/satellite/RHN-Register
     dest: /var/tmp

  - name: Create a directory if it does not exist
    file:
     path: /etc/yum.repos.d/BACKUP
     state: directory
     mode: '0755'

#  - name: Shell yum clean all
#    shell: /usr/bin/yum clean all
#    args:
#      executable: /bin/bash
#      warn: no
#      creates: /etc/yum.repos.d/CentOS-Base.repo

#  - name: Shell copy repo files to BACKUP directory
#    shell: /usr/bin/mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/BACKUP
#    args:
#      executable: /bin/bash
#      warn: no
#      creates: /etc/yum.repos.d/BACKUP/CentOS-Base.repo

#  - name: Remove repository (and clean up left-over metadata)
#    yum_repository:
#      name: base/7/x86_64 extras/7/x86_64 updates/7/x86_64
#      state: absent
#      notify: yum-clean-metadata

#  - name: Remove file (delete file)
#    file:
#     path: /etc/yum.repos.d/*.repo
#     state: absent

  - name: YUM install RHN-Register PART I and pre-requisites from local file
    yum:
      name: /var/tmp/RHN-Register/libnl-1.1.4-3.el7.x86_64.rpm, /var/tmp/RHN-Register/m2crypto-0.21.1-17.el7.x86_64.rpm, /var/tmp/RHN-Register/pyOpenSSL-0.13.1-4.el7.x86_64.rpm, /var/tmp/RHN-Register/python-dmidecode-3.12.2-3.el7.x86_64.rpm, /var/tmp/RHN-Register/python-ethtool-0.8-8.el7.x86_64.rpm, /var/tmp/RHN-Register/python-gudev-147.2-7.el7.x86_64.rpm, /var/tmp/RHN-Register/python-hwdata-1.7.3-4.el7.noarch.rpm, /var/tmp/RHN-Register/yum-rhn-plugin-2.0.1-10.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-check-2.0.2-24.el7.x86_64.rpm, /var/tmp/RHN-Register/rhn-client-tools-2.0.2-24.el7.x86_64.rpm, /var/tmp/RHN-Register/rhnlib-2.5.65-8.el7.noarch.rpm, /var/tmp/RHN-Register/rhnsd-5.0.13-10.el7.x86_64.rpm, /var/tmp/RHN-Register/rhn-setup-2.0.2-24.el7.x86_64.rpm, /var/tmp/RHN-Register/rhn-client-tools-2.0.2-24.el7.x86_64.rpm
      state: present
      disable_gpg_check: yes

  - name: YUM install RHN-Register PART II and pre-requisites from local file
    yum:
      name: /var/tmp/RHN-Register/python2-rhn-check-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-rhnlib-2.9.5-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-rhn-client-tools-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-rhn-setup-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-client-tools-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-setup-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-check-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/yum-rhn-plugin-2.9.5-1.el7.noarch.rpm
      state: present
      disable_gpg_check: yes


## yum-rhn-plugin - disable GPG check
  - name: yum-rhn-plugin update GPG check 0 in /etc/yum/pluginconf.d/rhnplugin.conf
    lineinfile:
     path: /etc/yum/pluginconf.d/rhnplugin.conf
     insertafter: '#gpgcheck = 0'
     line: 'gpgcheck = 0'
     backup: yes

## RHN-register
  - name: rhn-register as with activation key
    rhn_register:
      state: present
      activationkey: 1-21ad0fddf8f510baf82b58788f384190
      server_url:  http://192.168.130.76/XMLRPC
#      channels: centos-7-base-x86_64

## RHN-register add software channels
#  - name: rhn-register add software base channels
#    rhn_register:
#      state: present
#      activationkey: 1-21ad0fddf8f510baf82b58788f384190
#      channels: 'Centos 7 Base x86_64'


## Spacewalk osad packages install
  - name: YUM install osad Spacewalk packages
    yum:
      name: /var/tmp/RHN-Register/python2-rhnlib-2.9.5-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-rhn-client-tools-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-setup-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-rhn-check-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-rhn-setup-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-client-tools-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/jabberpy-0.5-0.27.el7.noarch.rpm, /var/tmp/RHN-Register/python2-osa-common-5.11.107-1.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-check-2.9.36-1.el7.noarch.rpm, /var/tmp/RHN-Register/spacewalk-usix-2.9.1-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-spacewalk-usix-2.9.1-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-osad-5.11.107-1.el7.noarch.rpm, /var/tmp/RHN-Register/osad-5.11.107-1.el7.noarch.rpm
      state: present
      disable_gpg_check: yes

## Add SpaceWalk SSL certificate to host
  - name: Ansible copy SpaceWalk SSL cert to target server
    copy:
     src: /var/www/html/pub/RHN-ORG-TRUSTED-SSL-CERT
     dest: /usr/share/rhn/


## Spacewalk openscap client
  - name: YUM install spacewalk-oscap (openScap)
    yum:
      name: /var/tmp/RHN-Register/spacewalk-oscap-2.9.5-1.el7.noarch.rpm, /var/tmp/RHN-Register/python2-spacewalk-oscap-2.9.5-1.el7.noarch.rpm
      state: present
      disable_gpg_check: yes

## INSTALL 3RD-PARTY SOFTWARE
# Copy 3rd-Party dir from spacewalk to host
  - name:  Ansible copy /var/satellite/3rd-Party directory from Spacewalk to Target Server
    copy:
     src: /var/satellite/3rd-Party
     dest: /var/tmp


## RHN-Register clean up /var/tmp/RHN-Register working directory
#  - name: Clean-up remove /var/tmp/RHN-Register directory
#    file:
#     path: /var/tmp/RHN-Register
#     state: absent


## ADD FIREWALL RULES
# Firewalld - enable sftp/ssh services
  - name:  Firewalld enbable services
    firewalld:
       service: "{{ item }}"
       permanent: yes
       state: enabled
    loop:
      - ssh

## TIDY UP TEMPORARY WORKING DIRECTORIES
## RHN-Register clean up /var/tmp/RHN-Register working directory
  - name: Clean-up remove /var/tmp/RHN-Register directory
    file:
     path: /var/tmp/RHN-Register
     state: absent

## 3rd-Party clean up /var/tmp/3rd-Party working directory
  - name: Clean-up remove /var/tmp/RHN-Register directory
    file:
     path: /var/tmp/3rd-Party
     state: absent
