- hosts:  lnlxtst01
  tasks:
  - name:  Ansible copy RHN-Register folder from Spacewalk to Target Server
    copy:
     src: /var/satellite/RHN-Register
     dest: /var/tmp
  - name:  Create a directory if it does not exist
    file:
     path: /etc/yum.repos.d/BACKUP
     state: directory
     mode: '0755'
#  - name: Remove repository (and clean up left-over metadata)
#    yum_repository:
#      name: base/7/x86_64 extras/7/x86_64 updates/7/x86_64
#      state: absent
#     notify: yum-clean-metadata
  - name:  Install RHN software and dependencies
    file:
     path: /etc/yum.repos.d/BACKUP
     state: directory
  - name: Enable CENTOS repos(CentOS only)
    ini_file:
      dest: /etc/yum.repos.d/CentOS-Base.repo
      section: "{{ item }}"
      option: enabled
      value: 0
    with_items:
       - base
       - updates
       - extras
       - centosplus
    when:
       - (ansible_distribution == "CentOS")
       -   ansible_distribution_major_version == "7"
  - name: install libnl rpm from a local file
    yum:
      name: /var/tmp/RHN-Register/libnl-1.1.4-3.el7.x86_64.rpm, /var/tmp/RHN-Register/m2crypto-0.21.1-17.el7.x86_64.rpm, /var/tmp/RHN-Register/pyOpenSSL-0.13.1-4.el7.x86_64.rpm, /var/tmp/RHN-Register/python-dmidecode-3.12.2-3.el7.x86_64.rpm, /var/tmp/RHN-Register/python-ethtool-0.8-8.el7.x86_64.rpm, /var/tmp/RHN-Register/python-gudev-147.2-7.el7.x86_64.rpm, /var/tmp/RHN-Register/python-hwdata-1.7.3-4.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-check-2.0.2-24.el7.x86_64.rpm, /var/tmp/RHN-Register/rhn-client-tools-2.0.2-24.el7.x86_64.rpm, /var/tmp/RHN-Register/rhnlib-2.5.65-8.el7.noarch.rpm, /var/tmp/RHN-Register/rhnsd-5.0.13-10.el7.x86_64.rpm, /var/tmp/RHN-Register/rhn-setup-2.0.2-24.el7.x86_64.rpm, /var/tmp/RHN-Register/yum-rhn-plugin-2.0.1-10.el7.noarch.rpm
      state: present
