- hosts:  lnlxtst01
  tasks:
  - name:  Ansible copy RHN-Register folder from Spacewalk to Target Server
    copy:
     src: /var/satellite/RHN-Register
     dest: /var/tmp
  - name:  Create a directory if it does not exist
    file:
     path: /etc/yum.repos.d/BACKUP
     state: directory
     mode: '0755'
#  - name: Remove repository (and clean up left-over metadata)
#    yum_repository:
#      name: base/7/x86_64 extras/7/x86_64 updates/7/x86_64
#      state: absent
#     notify: yum-clean-metadata
  - name:  Install RHN software and dependencies
    file:
     path: /etc/yum.repos.d/BACKUP
     state: directory
  - name: Enable CENTOS repos(CentOS only)
    ini_file:
      dest: /etc/yum.repos.d/CentOS-Base.repo
      section: "{{ item }}"
      option: enabled
      value: 0
    with_items:
       - base
       - updates
       - extras
       - centosplus
    when:
       - (ansible_distribution == "CentOS")
       -   ansible_distribution_major_version == "7"
