- hosts: lnlxgk01
  vars:



  tasks:
## REGISTER SERVER TO SPACEWALK
  - name: Ansible copy RHN-Register folder from Spacewalk to Target Server
    copy:
     src: /var/satellite/RHN-Register
     dest: /var/tmp

  - name: Create a directory if it does not exist
    file:
     path: /etc/yum.repos.d/BACKUP
     state: directory
     mode: '0755'

#  - name: Shell copy repo files to BACKUP directory
#    shell: cp /etc/yum.repos.d/*.repo /etc/yum.repos.d/BACKUP

#  - name: Remove repository (and clean up left-over metadata)
#    yum_repository:
#      name: base/7/x86_64 extras/7/x86_64 updates/7/x86_64
#      state: absent
#      notify: yum-clean-metadata

#  - name: Remove file (delete file)
#    file:
#     path: /etc/yum.repos.d/*.repo
#     state: absent

  - name: YUM install RHN-Register and pre-requisites from local file
    yum:
      name: /var/tmp/RHN-Register/libnl-1.1.4-3.el7.x86_64.rpm, /var/tmp/RHN-Register/m2crypto-0.21.1-17.el7.x86_64.rpm, /var/tmp/RHN-Register/pyOpenSSL-0.13.1-4.el7.x86_64.rpm, /var/tmp/RHN-Register/python-dmidecode-3.12.2-3.el7.x86_64.rpm, /var/tmp/RHN-Register/python-ethtool-0.8-8.el7.x86_64.rpm, /var/tmp/RHN-Register/python-gudev-147.2-7.el7.x86_64.rpm, /var/tmp/RHN-Register/python-hwdata-1.7.3-4.el7.noarch.rpm, /var/tmp/RHN-Register/rhn-check-2.0.2-24.el7.x86_64.rpm, /var/tmp/RHN-Register/rhn-client-tools-2.0.2-24.el7.x86_64.rpm, /var/tmp/RHN-Register/rhnlib-2.5.65-8.el7.noarch.rpm, /var/tmp/RHN-Register/rhnsd-5.0.13-10.el7.x86_64.rpm, /var/tmp/RHN-Register/rhn-setup-2.0.2-24.el7.x86_64.rpm, /var/tmp/RHN-Register/yum-rhn-plugin-2.0.1-10.el7.noarch.rpm
      state: present
      disable_gpg_check: yes

## RHN-register
  - name: rhn-register as with activation key
    rhn_register:
      state: present
      activationkey: 1-21ad0fddf8f510baf82b58788f384190
      server_url:  http://192.168.130.76/XMLRPC

## RHN-register add software channels
  - name: rhn-register add software base channels
    rhn_register:
      state: present
      activationkey: 1-21ad0fddf8f510baf82b58788f384190
      channels: centos-7-base-x86_64

## RHN-Register clean up /var/tmp/RHN-Register working directory
  - name: Clean-up remove /var/tmp/RHN-Register directory
    file:
     path: /var/tmp/RHN-Register
     state: absent


## ADD USERS AND GROUPS
# Add devs group
  - name: Add devs group
    group:
     name: devs
     state: present

# Add ECA user/group
  - name: Add ECA user group
    user:
     name: ECA
     state: present


## INSTALL 3RD-PARTY SOFTWARE
# yum install git @ latest
  - name: YUM install git @ latest
    yum:
      name:  git
      state: present

# Copy 3rd-Party dir from spacewalk to host
  - name:  Ansible copy /var/satellite/3rd-Party directority from Spacewalk to Target Server
    copy:
     src: /var/satellite/3rd-Party
     dest: /var/tmp

# Yum install XRDP and selinux files.
  - name: install XRDP and its dependencies from local file
    yum:
      name: selinux-policy, selinux-policy-devel, selinux-policy-targeted, /var/tmp/3rd-Party/xrdp-selinux-0.9.11-5.el7.x86_64.rpm, /var/tmp/3rd-Party/xrdp-0.9.11-5.el7.x86_64.rpm, /var/tmp/3rd-Party/xorgxrdp-0.2.11-1.el7.x86_64.rpm, m4
      state: present
      disable_gpg_check: yes

# Firewalld - enable xrdp services/ports
  - name:  Firewalld enbable ports for XRDP
    firewalld:
       port: "{{ item }}"
       permanent: yes
       immediate: yes
       state: enabled
    loop:
      - 3389/tcp
      - 5000/tcp
      - 5001/tcp
      - 4200/tcp
      - 4300/tcp
      - 5003/tcp
      - 5103/tcp


# Yum install dotnet dependencies from 3rd-Party dir
  - name: install dotnet and dependencies from a local file
    yum:
      name: /var/tmp/3rd-Party/aspnetcore-runtime-2.2.4-x64.rpm, /var/tmp/3rd-Party/bcompare-4.3.2.24472.x86_64.rpm, /var/tmp/3rd-Party/code-1.40.1-1573664332.el7.x86_64.rpm, /var/tmp/3rd-Party/dbeaver-ce-6.2.5-stable.x86_64.rpm, /var/tmp/3rd-Party/dotnet-host-2.2.4-x64.rpm, /var/tmp/3rd-Party/dotnet-hostfxr-2.2.4-x64.rpm, /var/tmp/3rd-Party/dotnet-runtime-2.2.4-x64.rpm, /var/tmp/3rd-Party/dotnet-runtime-deps-2.2.4-rhel.7-x64.rpm, /var/tmp/3rd-Party/dotnet-sdk-2.2.203-x64.rpm, /var/tmp/3rd-Party/code-1.41.1-1576681965.el7.x86_64.rpm
      state: present
      disable_gpg_check: yes



## GOOGLE CHROME

# Yum install Google Chrome dependencies from 3rd-Party dir
  - name: install Google Chrome and dependencies from a local file
    yum:
      name: /var/tmp/3rd-Party/fontpackages-filesystem-1.44-8.el7.noarch.rpm, /var/tmp/3rd-Party/libappindicator-12.10.0-13.el7.x86_64.rpm, /var/tmp/3rd-Party/libappindicator-gtk3-12.10.0-13.el7.x86_64.rpm, /var/tmp/3rd-Party/libdbusmenu-16.04.0-4.el7.x86_64.rpm, /var/tmp/3rd-Party/libdbusmenu-gtk2-16.04.0-4.el7.x86_64.rpm, /var/tmp/3rd-Party/libdbusmenu-gtk3-16.04.0-4.el7.x86_64.rpm, /var/tmp/3rd-Party/liberation-fonts-1.07.2-16.el7.noarch.rpm, /var/tmp/3rd-Party/liberation-fonts-common-1.07.2-16.el7.noarch.rpm, /var/tmp/3rd-Party/liberation-narrow-fonts-1.07.2-16.el7.noarch.rpm, /var/tmp/3rd-Party/liberation-sans-fonts-1.07.2-16.el7.noarch.rpm, /var/tmp/3rd-Party/liberation-serif-fonts-1.07.2-16.el7.noarch.rpm, /var/tmp/3rd-Party/libindicator-12.10.1-6.el7.x86_64.rpm, /var/tmp/3rd-Party/libindicator-gtk3-12.10.1-6.el7.x86_64.rpm
      state: present
      disable_gpg_check: yes





## Install/enable via systemctl osad service
#  - name: Enable start the osad service via systemctl osad used by Spacewalk to action on clients
#    service:
#     name=osad
#     state=restarted
#     enabled=yes
# RPMS /var/tmp/RHN-Register/python2-osad-5.11.107-1.el7.noarch.rpm /var/tmp/RHN-Register/osad-5.11.107-1.el7.noarch.rpm

## Configure BASH for users better history
#  - name: Add better BASH settings for history
#    lineinfile:
#     path: /etc/sysctl.conf
#     line: fs.inotify.max_user_watches=524288
#     create: yes


## USER/GROUP SETUP
  - name: Add devs group
    group:
     name: devs
     state: present

##
  - name: Add max_user_watch settings for Visual Studio
    lineinfile:
     path: /etc/sysctl.conf
     line: fs.inotify.max_user_watches=524288
     create: yes


  - name: Add dotnet shared library directory
    file:
     path: /usr/share/dotnet/sdk/NuGetFallbackFolder
     state: directory
     mode: '0755'

  - name:  Add custom NuGet config file /var/satellite/custom-files/NuGet.Config
    copy:
     src: /var/satellite/custom-files/NuGet.Config
     dest: /var/tmp
