- hosts: TARGET
  tasks:

  - name: Use uri to check t'internet
    uri:
      url: http://scootersoftware.com
      return_content: no
      timeout: 10
    register:  tinternet_disabled
#    failed_when: ( result.rc not in [ 0, 68 ] )
#    failed_when: "{{ tinternet_disabled.failed == 'true' }}"
    ignore_errors: true
  - debug:
      msg: "{{ tinternet_disabled.failed }}"
      msg: "{{ tinternet_disabled }}"
#      msg: "{{ tinternet_disabled }}"


  - name: Rebooting ...
    command: sleep 10 && shutdown -r now "Reboot required for updated kernel"
    async: 1
    poll: 0
#    sudo: true
    ignore_errors: true
#    when: not(tinternet_disabled.failed('true') != -1)
#    when: tinternet_disabled.failed is search('false')
#    when: tinternet_disabled.stdout.find("Status code was -1 and not") != -1
#    when: not "{{ tinternet_disabled == 'Status code was -1 and not' }}"
#    when: '"Status code was -1 and not" in tinternet_disabled.stdout'
    failed_when: not "tinternet_disabled.failed not in [ true ] )"
    register: rebooting
#      msg: "{{ tinternet_disabled.failed }}"

##
#  - name: Add max_user_watch settings for Visual Studio
#    lineinfile:
#     path: /etc/sysctl.conf
#     line: fs.inotify.max_user_watches=524288
#     create: yes

#  - name:  Add custom ECA snmpd.conf (adding ECA_international.com community and enable .1 tree access)
#    copy:
#     src: /var/satellite/custom-files/ECA_snmpd.conf
#     dest: /etc/snmp/snmpd.conf
#     backup: yes
