---
- hosts: TARGET
  user: root
  vars:

  handlers:
  - name: "Restart sshd"
    service:
      name: "sshd"
      state: "restarted"

  tasks:
  - include_vars: groups.yml
  - include_vars: users.yml

  - name: Create groups ahead of accounts
    group:
     name: "{{ item.groups }}"
     state: present
    with_items:
      - "{{ admin_groups }}"
      - "{{ dev_groups }}"

#  - name: Add users | create users, shell, home dirs
#    user: 
#     name: "{{ item.login }}"
#     shell: /bin/bash
#     groups: "{{ item.groups_member }}"
#     createhome: yes
#     comment: "{{ item.login }}"
#    with_items:
#      - "{{ admin_users }}"
#      - "{{ dev_users }}"

  - include_vars: users.yml
  - name: Add sp_users accounts locally
    user:
      name: "{{ item.login }}"
      groups: "{{ item.groups }}"
      shell: /bin/bash
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      comment: "{{ item.login }}"
      append: yes
      password: "{{ item.password }}"
#      update_password: on_create
    with_items:
      - "{{ admin_users }}"
      - "{{ dev_users }}"


#  - name: Setup | authorized key upload
#    authorized_key: user={{ item.username }}
#      key="{{ lookup('file', 'pub_keys/{{ item.login }}.pub') }}"
#      path='/home/{{ item.username }}/.ssh/authorized_keys'
#      manage_dir: no
#    with_items: '{{ dev_users }}'

  - name: Adding devs_users to /etc/sudoers
    lineinfile:
      owner: root
      group: root
      dest: /etc/sudoers
      backup: yes
      validate: /usr/sbin/visudo -cf %s
      line: '{{ item }}'
    with_items:
      - ''
      - '## Developers'
      - 'Cmnd_Alias DEVS = /bin/firewall-cmd, /bin/systemctl, /sbin/reboot, /usr/bin/update-ca-trust extract, /usr/bin/cp *.crt /etc/pki/tls/certs, /usr/bin/ln -sv /etc/pki/tls/certs/*.crt /etc/pki/tls/certs/*.0, /bin/openssl x509 -in /etc/pki/tls/certs/*.crt -noout -hash, /usr/bin/cp *.crt /etc/pki/ca-trust/source/anchors/'
      - '%devs          ALL = NOPASSWD: DEVS, sudoedit /etc/hosts'

# Add sp_users entries to /etc/sudoers
  - name: Adding sp_users to /etc/sudoers
    lineinfile:
      owner: root
      group: root
      dest: /etc/sudoers
      backup: yes
      validate: /usr/sbin/visudo -cf %s
      line: '{{ item }}'
    with_items:
      - ''
      - '## sp_users'
      - 'Cmnd_Alias SP_USERS = /bin/firewall-cmd, /bin/systemctl, /sbin/reboot, /usr/bin/vi /etc/hosts, /bin/vim /etc/hosts, /usr/bin/su -'
      - '%sp_users      ALL=(ALL)        SP_USERS'

  - name: "Disable root login via SSH"
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin yes"
    notify: "Restart sshd"
...
